# Generated by Django 4.1 on 2024-06-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_alter_course_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.studentdetail",
            ),
        ),
    ]
